### ISSUE TITLE
Update the user manual

### ISSUE THREAD

**Issue by djdupre** [avidant/test-bayes#54]
How do you run the tests in `test-bayes/src/test`? Running the `mvn test` does not run the tests. Can test-bayes be used to run its own tests? If so, how?

I'm filing this issue as part of the assignment listed here: https://courses.cs.washington.edu/courses/cse403/18sp/projects/proj08b-address-feedback.html

**Comment by avidant** [comment]
Thank you for catching that. Our tests should run with `mvn test`. I just created a Pull Request that fixes that.
