### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by WilliamCao13** [avidant/test-bayes#65]
Feedback for [this assignment](https://courses.cs.washington.edu/courses/cse403/18sp/projects/proj08b-address-feedback.html)

### Administrative Stuff
- There seems to be a lot of active branches. Many of them are merged, but some branches like ```bayes``` haven't been touched for a very long time. Perhaps it would help to clean up the project by deleting some branches that have already been merged and/or are not maintained.
- A portion of the Pull Requests are for reports. This can make it more difficult to find changes to the source code later on. **Labels** in GitHub could be helpful for differentiating changes to the source code and reports.

### Documentation
- In ```Probability.java```, you don't mention that ```toString()``` will return the simplified version of the probability in the documentation. If that's expected behavior, it should be mentioned.
- In ```TestLogReader.java``` and ```TestLogWriter.java```, consider adding descriptions to the exceptions thrown.
- Small typos in ```Probability.java```
  - Second constructor of Probability: ```@param numerator```'s description has a typo, ```Numberator```.
  - ```addNumerator``` function: ```@param num```'s description has a typo, ```numereator```.
  - ```compareTo``` function: ```@return```'s description has a typo, ```Probabiliy```.
- Typos in ```Bayes.java```: ```probabilty``` is used instead of ```probability```. 

### Testing
- In ```ProbabilityTest.java```, there is nothing that tests ```hashCode()``` even though you test equality between the Probabilities.

### Refactoring
- In ```Bayes.java```:
  - ```buildPasscond()``` and ```buildFailcond()``` reuse a lot of the same code. You could probably factor it out into another function.
  - ```buildPasscond()``` explicitly declares the type. Since it looks like you're using Java 8, leaving out the types between the ```<>``` could help with potential refactoring in the future if you were to change the types.
  - Since ```Bayes.java``` and ```Probability.java``` are in the same package, there is no need for ```import edu.uw.cse.testbayes.model.Probability;```.
  - Both constants ```NUMERATOR``` and ```DENOMINATOR``` could be made private since they are not used elsewhere.
  - Smaller suggestion: use CamelCasing for ```buildPasscond()``` and ```buildFailcond()```
- The exceptions caught in the constructors of ```IndividualClassRandomRunner.java``` and ```IndividualClassRunner.java``` can be collapsed into one statement since the exception bodies are identical.
- There is a lot of reused code between ```IndividualClassRandomRunner.java``` and ```IndividualClassRunner.java```.

### Potential Issues
- In ```Probability.java```, consider using ```Double.compare()``` instead of ```>``` and ```<``` when comparing ```thisvalue``` and ```othervalue```.

**Comment by avidant** [comment]
**Administrative Stuff**

- Some of these branches are currently being worked on. We do delete old branch infrequently, but we will go over these again and will delete the ones that aren't useful any more
- This has been done and was visible in yesterday's report

** Documentation**

- Will look into - #67
- Will do - #68
- #69
- #69

**Testing**
1. #70

**Refactoring**

- #62 addresses some of this. Also #71
- #63 already exists
- `IndividualClassRandomRunner.java` is only for evaluation. Will be gone in the final result

**Potential Issues**

- #61 addresses this
